### ISSUE TITLE
Switchoff delay also runs when door is closed

### ISSUE THREAD

**Issue by Paulxp** [Tommrodrigues/homebridge-http-garage#5]
Hi,
i am so happy to have this plugin installed and working. I have two Sonoff SV devices, isolated outputs ale soldiered to remote controller button 1 for open and button 2 for close door (PulseTime is set to 20 on both Sonoff SV relays). No real status installed because the gate is shared, so your plugin best fits to my scenario.

My config looks like this:
```
{
    "accessory": "GarageDoorOpener",
    "name": "Door-G",
    "openURL": "http://192.168.185.101/cm?cmnd=Power%20On",
    "closeURL": "http://192.168.185.147/cm?cmnd=Power%20On",
    "openTime": "16",
    "closeTime": "15",
    "switchOff": "true",
    "switchOffDelay": "36",
    "autoLock": "true",
    "autoLockDelay": "36"
}
```
The issue is that your plugin count down switchoffdelay time also when garage door is in closed status. 

Example: I open garage door (opening takes 16 second - notification about open status received) and after garage door is opened i immediately close the garage door (closing takes 15 seconds - notifications about closed status received). Total time is approx 32 second from open to closed state. But in 36th second (based on my switchOffDelay i see that closed garage door is again in status closing (it takes again 15 seconds - new notification about closed garage door received). 

Is there any option how to stop/skip switchoffdelay timer when garage door is closed before switchoffdelay time?

**Comment by phenotypic** [comment]
Hi there, I'm not sure what you're referring to by `switchOff` and `switchOffDelay` - neither of those are mentioned in the `README` for this plugin.

Instead, I think your problem is with `autoLock`.  As described in the `README`, when `autoLock` is enabled and the door is opened, it will wait the number of seconds in `autoLockDelay` then trigger the door to close. In the situation you described, you opened the door and then closed it manually. But, because `autoLock` is enabled, `36` seconds after you initially opened the door, it triggered a second close.

The solution is either to have `autoLock` disabled and close the door manually every time, or leave it enabled and resist manually closing the door after you've opened it. 

Admittedly, it would be nice to have `autoLock` disable itself temporarily when it sees the door has been closed manually before `autoLockdDelay` is reached. Unfortunately, though, I don't currently have the time or incentive to code this in myself, but it's something I might look into in the future. In the meantime, feel free to fork the plugin, make the changes, and open a pull request!
